---
title: "Untitled"
author: "Reza Dwi Utomo"
date: "28/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(ggfortify)
library(lubridate)
```


```{r}
fnb <- read.csv("data/data-train.csv")
fnb
```

```{r}
fnb <- fnb %>% select(transaction_date, receipt_number)
fnb$transaction_date <- ymd_hms(fnb$transaction_date)
```

```{r}
fnb <- fnb %>% 
  mutate(transaction_date = floor_date(x = .$transaction_date, unit = "hour"))

```

```{r}
fnb <- fnb %>% 
  group_by(transaction_date) %>% 
  summarise(visitor = n_distinct(receipt_number)) %>% 
  ungroup()
```

```{r}
min_date <- min(fnb$transaction_date)
max_date <- max(fnb$transaction_date)

start_val <- make_datetime(year = year(min_date), month = month(min_date), day = day(min_date), hour = hour(hms("00:00:00")))
end_val <- make_datetime(year = year(max_date), month = month(max_date), day = day(max_date), hour = hour(max_date))

fnb_pad <- padr::pad(x = fnb, start_val = start_val, end_val = end_val)


```

```{r}
fnb_pad$visitor <- replace_na(fnb_pad$visitor, 0)
```

```{r}
fnb_pad$date <- ymd(paste(year(fnb_pad$transaction_date),
                      month(fnb_pad$transaction_date), 
                      day(fnb_pad$transaction_date), 
                      sep = "-"))
fnb_pad$time <- hms(paste(hour(fnb_pad$transaction_date), 0, 0, sep = ":"))

fnb_pad$day <- wday(x = fnb_pad$transaction_date, label = T, abbr = F)
```

```{r}
fnb_pad %>% ggplot(aes(x = hour(time), y = visitor)) +
  geom_col(aes(fill = day)) +
  theme_minimal() +
  labs(title = "Number of visitors",
       x = "Hour",
       y = "Number of visitors",
       fill = "Day")
```

# Modelling

```{r}
fnb_ts <- ts(data = fnb_pad$visitor, frequency = 24*7)
autoplot(fnb_ts)
```

```{r}
fnb_dec <- decompose(x = fnb_ts, type = "additive") 
fnb_dec %>% autoplot()
```

```{r}
hist(fnb_dec$random)
shapiro.test(fnb_dec$random)
```

```{r}
Box.test(fnb_dec$random)
```

```{r}
# split train-validation 1 seasonal
train <- head(fnb_ts, length(fnb_ts) - 24 * 7)
validation <- tail(fnb_ts, 24 * 7)
```

```{r}
model_holt<- HoltWinters(train, seasonal = "additive")
forecast_holt <- forecast::forecast(model_holt, h = 24 * 7)
MLmetrics::MAE(y_pred = forecast_holt$mean, y_true = validation)
TSstudio::plot_forecast(forecast_holt) #, title = "Model Complex Seasonality")
```

```{r}
TSstudio::test_forecast(actual = fnb_ts, forecast.obj = forecast_holt,
                        train = train, test = validation)
```

```{r}
model_arima <- forecast::auto.arima(train)
forecast_arima <- forecast::forecast(model_arima, h = length(validation))
TSstudio::plot_forecast(forecast_arima)
MLmetrics::MAE(y_pred = forecast_arima$mean, y_true = validation)
```

